server:
  port: 8001

mybatis-plus:
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations: classpath:/mapper/*Mapper.xml

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    # mysql驱动包
    #   url: jdbc:mysql://localhost:3306/db2019
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false      #mysql5.7以后安全      # 数据库名称
    username: root
    password: 123456

# erueka:
  #client:
  #  register-with-eureka: true
  #  fetchRegistry: true
  #  service-url:
  #    defaultZone: http://localhost:7001/eureka/

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
    #  defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示IP地址



#mybatis:
 # mapper-locations: classpath:mapper/*.xml
 # type-aliases-package: com.atguigu.springcloud.entities  # entity 别名类所在包