server:
  port: 9527

spring:
  application:
    name: cloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9002.com
    prefer-ip-address: true


zuul:
   ignored-services: cloud
   routes:
     mydept.serviceId: cloud
     mydept.path: /haha/**


  #ignored-services: microservicecloud-dept
  #prefix: /atguigu
 # ignored-services: "*"

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

