server:
  port: 80
spring:
  application:
    name: cloud-orderfegin-service

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: consumfeign
#erueka:
 # client:
 #  service-url:
    # defaultZone: http://localhost:7001/eureka/
