server:
  port: 80
spring:
  application:
    name: cloud-feign-service

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: microservicecloud-dept8001gfeing
#erueka:

ribbon:
  ReadTimeout: 5000
  ConnecTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
